{% set name = "econml" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/econml-{{ version }}.tar.gz
  sha256: de7a168133d6a92fe967fce79172bdc9c298de9b603afa0fb868dc1797323aff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [s390x or py>311]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - wheel
    - setuptools
  run:
    - lightgbm
    - joblib >=0.13.0
    - numpy
    - numba
    - pandas >1.0
    - python
    - scipy >1.4.0
    - scikit-learn >=1.0,<1.5
    - shap >=0.38.1,<0.44.0
    - sparse
    - statsmodels >=0.10

test:
  imports:
    - econml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Microsoft/EconML
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  description: |
    EconML is a Python package for estimating heterogeneous treatment effects from observational data via
    machine learning. This package was designed and built as part of the ALICE project at Microsoft
    Research with the goal to combine state-of-the-art machine learning techniques with econometrics to 
    bring automation to complex causal inference problems.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://econml.azurewebsites.net/
  dev_url: https://github.com/Microsoft/EconML

extra:
  recipe-maintainers:
    - manuelwalserqc
    - norbertstoopqc
    - xhochy
