{% set name = "econml" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/econml-{{ version }}.tar.gz
  sha256: 9e4fa61b5ef4bcd49138ed98ebedb1ac900ee18b679a393859fc7050f2846e2a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python >=3.6
  run:
    - dowhy
    - python-graphviz
    - joblib >=0.13.0
    - numba !=0.42.1
    - numpy
    - pandas
    - python
    - scikit-learn >=0.24
    - scipy >1.4.0
    - shap ~=0.38.1
    - sparse
    - statsmodels >=0.9

test:
  imports:
    - econml
    - econml.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Microsoft/EconML
  summary: This package contains several methods for calculating Conditional Average Treatment Effects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MohammedAjilQC
    - norbertstoopqc
